variables:
  PROJECT_NAME: be-service-auth
  REPO_NAME: gitlab.com/luru-norton/be-service-auth.git
  SSH_HOST: ${SSH_HOST_DEV}
  SSH_USER: ${SSH_USER_DEV}
  SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY_DEV}

stages:
  - build

building:
  stage: build
  script:
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - ls -la $GOPATH/src/ # Tambahkan baris ini untuk mencetak isi direktori $GOPATH/src
    - cd $GOPATH/src/$REPO_NAME || exit  # Tambahkan 'exit' untuk menghentikan eksekusi jika perpindahan direktori gagal
    - pwd  # Tambahkan baris ini untuk mencetak direktori saat ini
    - GOOS=linux GOARCH=amd64 go build -ldflags '-linkmode external -w -extldflags "-static"' -o ${PROJECT_NAME}
    - echo "Builded"
  only:
    - dev
  artifacts:
    paths:
      - ${PROJECT_NAME}
    expire_in: 5 min