stages:
  - build

variables:
  BINARY_NAME: "be-service-auth"  # Ganti dengan nama binary yang sesuai dengan proyek Anda

before_script:
  - export GOPATH=$CI_PROJECT_DIR/go
  - export PATH=$GOPATH/bin:$PATH

build:
  stage: build
  script:
    - go build -o $BINARY_NAME

artifacts:
  paths:
    - $BINARY_NAME
