stages:
  - build
  - deploy

variables:
  BINARY_NAME: "myapp"
  SERVER_IP: "your-droplet-ip"
  SERVER_USER: "your-server-username"
  SERVER_PATH: "/path/to/remote/directory"

before_script:
  - export GOPATH=$CI_PROJECT_DIR/go
  - export PATH=$GOPATH/bin:$PATH

build:
  stage: build
  script:
    - apt-get update -qy && apt-get install -y golang
    - go build -o $BINARY_NAME
  artifacts:
    paths:
      - $BINARY_NAME

deploy:
  stage: deploy
  only:
    - dev
  script:
    - scp $BINARY_NAME $SERVER_USER@$SERVER_IP:$SERVER_PATH
    - ssh $SERVER_USER@$SERVER_IP 'sudo systemctl stop your-app-service'
    - ssh $SERVER_USER@$SERVER_IP 'mv $SERVER_PATH/$BINARY_NAME /path/to/your/app'
    - ssh $SERVER_USER@$SERVER_IP 'sudo systemctl start your-app-service'
