variables:
  PROJECT_NAME: be-service-auth
  REPO_NAME: gitlab.com/luru-norton/be-service-auth.git
  #GIT_SUBMODULE_STRATEGY: recursive

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  cache:
    paths:
      - .go/pkg/mod/

stages:
  # - test
  - build
  - deploy

build-old:
  stage: build
  cache:
    key: ${PROJECT_NAME}
    paths:
      - ${PROJECT_NAME}
  script:
    - pwd
    - make build
    - echo "Built"
  only:
    - dev
  tags:
    - ssh

# ... (Bagian lain dari konfigurasi)
