variables:
  PROJECT_NAME: be-service-auth
  REPO_NAME: gitlab.com/luru-norton/be-service-auth.git

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  cache:
    paths:
      - .go/pkg/mod/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - pwd
    - make build  # Gantilah dengan perintah build sesuai dengan makefile Anda
    - echo "Built"
  only:
    - dev
  tags:
    - ssh

deploy:
  stage: deploy
  script:
    # Tambahkan langkah-langkah deploy sesuai dengan kebutuhan Anda
    - echo "Deploying...."
  only:
    - dev
  tags:
    - ssh