version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    networks:
      - Apps-Service-Dependencies-Cms
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: auth,product
    ports:
      - "3306:3306"
    networks:
      - Apps-Service-Dependencies-Cms

  redis-containers:
    image: redis:7.0.12
    ports:
      - "6379:6379"
    networks:
      - Apps-Service-Dependencies-Cms

  be-service-auth-container:
    image: reynaldojosuatogatorop/be-service-auth:dev
    ports:
      - "8882:8882"
    depends_on:
      - mariadb
      - redis-containers
      # - emqx
      - minio
    networks:
      - Apps-Service-Dependencies-Cms
    environment:
      - SERVER_PORT=8882
      - SERVER_PREFORK=false
      - SERVER_STRICTROUTING=false
      - SERVER_CASESENSITIVE=false
      - SERVER_BODYLIMIT=4194304
      - SERVER_CONCURRENCY=262144
      - SERVER_TIMEOUT_READ=5
      - SERVER_TIMEOUT_WRITE=10
      - SERVER_TIMEOUT_IDLE=120
      - SERVER_LOGLEVEL=debug
      - SERVER_GRPCPORT=58882
      - SERVER_BASEPATH=
      - SERVER_SESSIONEXPIRE=3600
      - DATABASE_HOST=mariadb
      - DATABASE_PORT=3306
      - DATABASE_DATABASE=auth
      - DATABASE_USER=root
      - DATABASE_PASSWORD=12345
      - DATABASE_PATH_MIGRATE=file://db/migration
      - DATABASE_SSLOPTIONS_SSLMODE=disable
      - REDIS_HOST=redis-containers
      - REDIS_PORT=6379
      - REDIS_MAXCONNECTION=80
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
      - REDIS_DATABASE=0
      - MESSAGE_BROKER_HOST=emqx
      - MESSAGE_BROKER_PORT=1883
      - BUCKET_CREDENTIAL_ACCESS_KEY=ROOTUSER
      - BUCKET_CREDENTIAL_SECRET_KEY=CHANGEME123
      - BUCKET_CREDENTIAL_DOMAIN=http://minio:9000
      - BUCKET_CREDENTIAL_REGION=ap-southeast-1
  be-service-product-management-container:
    image: reynaldojosuatogatorop/be-service-product-management:dev
    ports:
      - "8883:8883"
    depends_on:
      - mariadb
      - redis-containers
      # - emqx
      - minio
    networks:
      - Apps-Service-Dependencies-Cms
    environment:
      - SERVER_PORT=8882
      - SERVER_PREFORK=false
      - SERVER_STRICTROUTING=false
      - SERVER_CASESENSITIVE=false
      - SERVER_BODYLIMIT=4194304
      - SERVER_CONCURRENCY=262144
      - SERVER_TIMEOUT_READ=5
      - SERVER_TIMEOUT_WRITE=10
      - SERVER_TIMEOUT_IDLE=120
      - SERVER_LOGLEVEL=debug
      - SERVER_GRPCPORT=58882
      - SERVER_BASEPATH=
      - SERVER_SESSIONEXPIRE=3600
      - SERVER_RATE_USD_TO_IDR=15000
      - DATABASE_HOST=mariadb
      - DATABASE_PORT=3306
      - DATABASE_DATABASE=product
      - DATABASE_USER=root
      - DATABASE_PASSWORD=12345
      - DATABASE_PATH_MIGRATE=file://db/migration
      - DATABASE_SSLOPTIONS_SSLMODE=disable
      - REDIS_HOST=redis-containers
      - REDIS_PORT=6379
      - REDIS_MAXCONNECTION=80
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
      - REDIS_DATABASE=0
      - MESSAGE_BROKER_HOST=emqx
      - MESSAGE_BROKER_PORT=1883
      - BUCKET_CREDENTIAL_ACCESS_KEY=ROOTUSER
      - BUCKET_CREDENTIAL_SECRET_KEY=CHANGEME123
      - BUCKET_CREDENTIAL_DOMAIN=http://minio:9000
      - BUCKET_CREDENTIAL_REGION=ap-southeast-1

  swagger-ui-container:
    image: swaggerapi/swagger-ui
    ports:
      - "8884:8080"
    networks:
      - Apps-Service-Dependencies-Cms
    environment:
      - SWAGGER_JSON=/app/openapi/openapi-auth.yaml
    volumes:
      - ./openapi-submodule/.:/app/openapi

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    networks:
      - Apps-Service-Dependencies-Cms
    volumes:
      - D:\minio\data:/data
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=CHANGEME123
    command: server /data --console-address ":9090"

networks:
  Apps-Service-Dependencies-Cms:
