CREATE TABLE auth (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    dtm_crt TIMESTAMP NOT NULL DEFAULT NOW(),
    dtm_upd TIMESTAMP NOT NULL DEFAULT NOW()
);