name: CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Build
        run: |
          make build
          echo "Built"

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          echo "Deploying..."
          # Add your deployment steps here
