name: CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      PROJECT_NAME: be-service-auth
      REPO_NAME: gitlab.com/luru-norton/be-service-auth.git

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Build
        run: |
          make build
          echo "Built"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      PROJECT_NAME: be-service-auth
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Deploy
        run: |
          ls -la
          sudo mkdir -p /usr/local/etc/${PROJECT_NAME}-migration
          sudo cp db/migration/* /usr/local/etc/${PROJECT_NAME}-migration
          # Jangan perlu membuat direktori /usr/local/bin/${PROJECT_NAME}
          sudo cp ${GITHUB_WORKSPACE}/be-service-auth /usr/local/bin/${PROJECT_NAME}  # Sesuaikan dengan lokasi file build
          sudo systemctl start ${PROJECT_NAME}
          echo "Deployed"
