name: Deploy to AWS

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Build
        run: |
          make build
          echo "Built"

  deploy:
    needs: build
    runs-on: self-hosted
    env:
      PROJECT_NAME: be-service-auth
    steps:
      - name: Start GitLab Runner
        run: sudo gitlab-runner start
        
      - name: Deploy
        run: |
          ls -la
          sudo cp db/migration/* /usr/local/etc/${PROJECT_NAME}-migration
          sudo systemctl stop ${PROJECT_NAME}
          sudo cp ${PROJECT_NAME} /usr/local/bin/${PROJECT_NAME}
          sudo systemctl start ${PROJECT_NAME}
          echo "Deploying..."
          # Add your deployment steps here
